name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: yarn i
      - name: Running unit tests
        run: yarn test
      - name: Running linter
        run: yarn lint
      - name: Building app
        run: yarn build
      # - name: Deploying app
      #   run: yarn deploy
